version: '3'
services:
  keras:
    build: ./
    ports:
      - '8080:8080'
    volumes:
      - ./fapp:/app
      - conda-volume:/opt/conda/envs/
    environment:
      - RELOAD_FB=20
volumes:
  conda-volume: