name: fbcrawler
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _tflow_select=2.3.0
  - absl-py=0.8.0
  - astor=0.8.0
  - binutils_impl_linux-64=2.33.1
  - binutils_linux-64=2.33.1
  - blas=1.0
  - c-ares=1.15.0
  - ca-certificates=2019.11.28
  - certifi=2019.11.28
  - click=7.0
  - cycler=0.10.0
  - dbus=1.13.6
  - expat=2.2.5
  - flask=1.1.1
  - flask-compress=1.4.0
  - fontconfig=2.13.1
  - freetype=2.10.0
  - future=0.18.2
  - gast=0.2.2
  - gcc_impl_linux-64=7.3.0
  - gcc_linux-64=7.3.0
  - gettext=0.19.8.1
  - glib=2.58.3
  - google-pasta=0.1.7
  - grpcio=1.16.1
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - gxx_impl_linux-64=7.3.0
  - gxx_linux-64=7.3.0
  - h5py=2.9.0
  - hdf5=1.10.4
  - icu=58.2
  - intel-openmp=2019.4
  - itsdangerous=1.1.0
  - jinja2=2.10.3
  - jpeg=9c
  - keras=2.2.4
  - keras-applications=1.0.8
  - keras-base=2.2.4
  - keras-preprocessing=1.1.0
  - kiwisolver=1.1.0
  - ld_impl_linux-64=2.33.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libgpuarray=0.7.6
  - libiconv=1.15
  - liblapack=3.8.0
  - libpng=1.6.37
  - libprotobuf=3.9.2
  - libstdcxx-ng=9.1.0
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.9
  - mako=1.1.0
  - markdown=3.1.1
  - markupsafe=1.1.1
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.14
  - mkl_random=1.1.0
  - ncurses=6.1
  - nltk=3.4.5
  - numpy=1.17.2
  - numpy-base=1.17.2
  - openssl=1.1.1d
  - opt_einsum=3.1.0
  - pandas=0.25.3
  - patsy=0.5.1
  - pcre=8.43
  - pip=19.3.1
  - plotly=4.3.0
  - protobuf=3.9.2
  - pthread-stubs=0.4
  - pygpu=0.7.6
  - pyparsing=2.4.5
  - pyqt=5.9.2
  - python=3.6.9
  - python-dateutil=2.8.1
  - pytz=2019.3
  - pyyaml=5.1.2
  - qt=5.9.7
  - readline=7.0
  - retrying=1.3.3
  - scipy=1.3.1
  - setuptools=41.4.0
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.30.1
  - statsmodels=0.10.2
  - tensorboard=1.15.0
  - tensorflow=1.15.0
  - tensorflow-base=1.15.0
  - tensorflow-estimator=1.15.1
  - termcolor=1.1.0
  - theano=1.0.4
  - tk=8.6.8
  - tornado=6.0.3
  - webencodings=0.5.1
  - werkzeug=0.16.0
  - wheel=0.33.6
  - wrapt=1.11.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.4
  - yaml=0.1.7
  - zlib=1.2.11
  - pip:
    - chardet==3.0.4
    - fpdf==1.7.2
    - idna==2.8
    - joblib==0.14.0
    - matplotlib==3.1.1
    - requests==2.22.0
    - scikit-learn==0.22
    - seaborn==0.9.0
    - sklearn==0.0
    - urllib3==1.25.7
#prefix: /home/sarora/anaconda3/envs/fbcrawler

